/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Miguel
 */
public class CargaExitosa extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargaExitosa
     */
    private Principal principal = new Principal();
    public CargaExitosa(Principal principal) {
        initComponents();
        this.principal = principal;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLMENSAJEexitoso = new javax.swing.JLabel();
        jBsalirMENSAJE = new javax.swing.JButton();
        jLfondoalert = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMENSAJEexitoso.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        jLMENSAJEexitoso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMENSAJEexitoso.setText("Afiliado guardado con exito!");
        jPanel1.add(jLMENSAJEexitoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 220, 40));

        jBsalirMENSAJE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMAGENES/Imagenes/ACEPTARerror-01.png"))); // NOI18N
        jBsalirMENSAJE.setBorder(null);
        jBsalirMENSAJE.setContentAreaFilled(false);
        jBsalirMENSAJE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMAGENES/Imagenes/ACEPTARerrorIN-01.png"))); // NOI18N
        jBsalirMENSAJE.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMAGENES/Imagenes/ACEPTARerrorIN-01.png"))); // NOI18N
        jBsalirMENSAJE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirMENSAJEActionPerformed(evt);
            }
        });
        jPanel1.add(jBsalirMENSAJE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 210, 60));

        jLfondoalert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMAGENES/Imagenes/Joption-01.png"))); // NOI18N
        jPanel1.add(jLfondoalert, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -50, 410, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirMENSAJEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirMENSAJEActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirMENSAJEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsalirMENSAJE;
    private javax.swing.JLabel jLMENSAJEexitoso;
    private javax.swing.JLabel jLfondoalert;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
