/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.AdministrativoData;
import AccesoADatos.Conexion;
import Entidades.Administrativo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.JOptionPane;

public class VistaLogin extends javax.swing.JInternalFrame {

    private Principal principal = new Principal();
    private AdministrativoData admData;

    public VistaLogin(Principal principal) {
         this.principal = principal;
        initComponents();       
        admData = new AdministrativoData();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTUsuario = new javax.swing.JTextField();
        jBRegistrarse = new javax.swing.JButton();
        jIniciarSesion = new javax.swing.JButton();
        jTContrasena = new javax.swing.JPasswordField();
        jBCerrar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTUsuario.setText("Usuario");
        jTUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(jTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, -1));

        jBRegistrarse.setText("Registrarse");
        jBRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(jBRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jIniciarSesion.setText("Iniciar sesión");
        jIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, -1));

        jTContrasena.setText("Contraseña");
        getContentPane().add(jTContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, -1));

        jBCerrar.setText("X");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 40, -1));

        jLabelFondo.setPreferredSize(new java.awt.Dimension(410, 312));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuarioMouseClicked
        if (jTUsuario.getText().trim().equals("Usuario")) {
            jTUsuario.setText("");
        }
     
    }//GEN-LAST:event_jTUsuarioMouseClicked

    private void jBRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarseActionPerformed
        try {
            String usuario = jTUsuario.getText().trim();
            String contrasena = jTContrasena.getText().trim();

            if (jTUsuario.getText().isEmpty() || jTContrasena.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No debe haber campos vacios");
                return;
            }
            Administrativo administrativo = new Administrativo(usuario, contrasena);
            admData.altaAdministrativo(administrativo);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese valores enteros válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBRegistrarseActionPerformed

    private void jIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarSesionActionPerformed

        String usuario = jTUsuario.getText().trim();
        String contrasena = jTContrasena.getText().trim();
        if (!usuario.equals("") && !contrasena.equals("")) {

            Connection cn = Conexion.getConexion();
            try {
                PreparedStatement ps = cn.prepareStatement("SELECT  * FROM administrativo WHERE usuario = ? and  contrasena = ?");
                ps.setString(1, usuario);
                ps.setString(2, contrasena);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {

                    //principal.setVisible(true);
                    principal.establecerFondoEscritorio();
                    principal.habilitarBotones();

                } else {
                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos.");
                    jTUsuario.setText("Usuario");
                    jTContrasena.setText("Contraseña");
                }
            } catch (SQLException ex) {
                System.err.println("Error en el boton acceder " + ex);
                JOptionPane.showMessageDialog(null, "¡Error al iniciar sesión!, conectate con el Administrador");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos...");
        }
    }//GEN-LAST:event_jIniciarSesionActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBRegistrarse;
    private javax.swing.JButton jIniciarSesion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPasswordField jTContrasena;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
